/** SECTION2 — ADMIN (divider +12 fitur). */

export const adminSlides = [
  {
    id: 'admin-divider',
    section: 'admin',
    role: 'admin',
    layout: 'divider',
    sectionNo: 2,
    title: 'Tutorial Admin',
    description: 'Alur lengkap Admin: dari Login hingga Pengaturan.',
    sectionItems: [
      'Login',
      'Dashboard',
      'Data Siswa',
      'Guru & Wali Kelas',
      'Kalender Akademik',
      'Monitoring Presensi',
      'Rekap Bulanan',
      'Rekap Semester',
      'Statistik Kehadiran',
      'Library / Perpustakaan',
      'Riwayat & Log Aktivitas',
      'Pengaturan',
    ],
  },
  {
    id: 'admin-login',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah01',
    title: 'Login',
    description: 'Masuk menggunakan akun Admin yang dibuat di sistem. Username dipetakan ke email internal madrasah.',
    goal: 'Membuka sesi aman dan diarahkan ke Dashboard sesuai peran.',
    steps: [
      'Buka halaman aplikasi — panel login tampil pertama.',
      'Isi Username dan Password akun Admin.',
      'Tekan "Masuk Sekarang" (atau Enter).',
      'Berhasil → redirect otomatis ke Dashboard Presensi.',
      'Login lama? Panel "Pulihkan Sesi" muncul otomatis setelah ~12 detik.',
    ],
    watchouts: [
      'Password salah3 kali berturut? Tetap tenang — pesan error menampilkan saran, bukan detail akun.',
      'Jangan bagikan kredensial. Tutorial ini tidak pernah menampilkan token/password asli.',
    ],
    screen: 'login',
    screenTable: {
      caption: 'Form login',
      headers: ['Field', 'Isi demo'],
      rows: [
        ['Username', 'admin.demo'],
        ['Password', '•••••••• (tidak ditampilkan)'],
        ['Aksi', 'Masuk Sekarang'],
      ],
    },
  },
  {
    id: 'admin-dashboard',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah02',
    title: 'Dashboard Presensi',
    description: 'Ringkasan kehadiran hari ini seluruh kelas: KPI, tren, komposisi, dan peringatan dalam satu layar.',
    goal: 'Melihat "big picture" harian tanpa membuka banyak menu.',
    steps: [
      'Pita KPI: Total Siswa, Hadir, Izin, Sakit, Alfa (hari ini).',
      'Tab kelas untuk memfilter (Semua Kelas / per kelas).',
      'Strip "Perlu perhatian": kelas yang belum presensi & jumlah Alfa.',
      'Grafik Tren Kehadiran: mode7 Hari / Bulanan / Tahunan.',
      'Donat Komposisi Hari Ini + daftar siswa tidak hadir.',
      'Aksi cepat: Input Presensi, Rekap, Data Siswa, Kalender.',
    ],
    watchouts: [
      'Data diperbarui real-time saat guru menekan Simpan Presensi.',
      'Angka Hadir hari ini hanya menghitung kelas yang sudah submit.',
    ],
    screen: 'dashboard-admin',
    screenTable: {
      caption: 'KPI hari ini (22 Sep2026)',
      headers: ['Metric', 'Nilai'],
      rows: [
        ['Total Siswa', '32 (3 kelas)'],
        ['Hadir', '17 ·85% kehadiran'],
        ['Izin / Sakit / Alfa', '1 /2/0'],
        ['Monitoring', '2 dari3 kelas sudah presensi'],
      ],
    },
  },
  {
    id: 'admin-siswa',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah03',
    title: 'Data Siswa (Master Data)',
    description: 'Sumber data utama seluruh modul. Siswa aktif muncul di form presensi, rekap, dan kartu perpustakaan.',
    goal: 'Menjaga daftar siswa akurat: tambah, edit, mutasi, dan impor massal.',
    steps: [
      'Buka menu Data Siswa → daftar siswa tampil (filter kelas & pencarian).',
      'Tambah manual: "+ Tambah Siswa", isi NISN, nama, jenis kelamin, kelas.',
      'Impor massal: "Upload Excel" — unduh template dulu, jangan ubah nama kolom.',
      'Mutasi keluar untuk siswa pindah; hapus permanen hanya bila salah input.',
      'Status "active" menentukan apakah siswa muncul di form presensi.',
    ],
    watchouts: [
      'NISN harus unik — duplikat akan ditolak.',
      'Mutasi/perubahan kelas berdampak ke rekap: lakukan di awal tahun ajaran.',
    ],
    screen: 'siswa',
    screenTable: {
      caption: 'Contoh daftar siswa kelas5A',
      headers: ['NISN', 'Nama', 'Kelas', 'Status'],
      rows: [
        ['0072341501', 'Ahmad Fauzan', '5A', 'Aktif'],
        ['0072341506', 'Nabila Putri', '5A', 'Aktif'],
        ['0072341507', 'Rizky Maulana', '5A', 'Aktif'],
        ['0072341509', 'Yusuf Ibrahim', '5A', 'Aktif'],
      ],
      note: '32 siswa aktif total · data fiktif demo',
    },
  },
  {
    id: 'admin-guru',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah04',
    title: 'Guru & Wali Kelas',
    description: 'Kelola akun login guru dan penugasan wali kelas — kunci pembagian akses Input Presensi.',
    goal: 'Memastikan setiap kelas punya wali kelas yang bisa mengisi presensi.',
    steps: [
      'Buka menu Guru & Wali Kelas.',
      'Tambah akun: username, password awal, nama, role, wali kelas, NIP.',
      'Role tersedia: Admin, Guru, Pustakawan, Guru & Pustakawan.',
      'Wali kelas hanya boleh1 kelas (satu-satunya kelas yang bisa dipilihnya).',
      'Impor massal via Upload Excel memakai template resmi.',
    ],
    watchouts: [
      'Password awal dibagikan lalu guru menggantinya — jangan simpan di catatan publik.',
      'Menghapus akun guru tidak menghapus riwayat presensi yang pernah ia input.',
    ],
    screen: 'guru',
    screenTable: {
      caption: 'Daftar akun',
      headers: ['Nama', 'Role', 'Wali Kelas'],
      rows: [
        ['Siti Rahmawati', 'Guru', '5A'],
        ['Dewi Lestari', 'Guru', '5B'],
        ['Agus Setiawan', 'Guru', '6A'],
        ['Nur Aini', 'Pustakawan', '—'],
        ['Budi Santoso', 'Admin', '—'],
      ],
    },
  },
  {
    id: 'admin-kalender',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah05',
    title: 'Kalender Akademik',
    description: 'Penanda hari masuk & libur. Rekap dan dashboard hanya menghitung hari efektif.',
    goal: 'Menjaga perhitungan rekap akurat (libur tidak dihitung, akhir pekan otomatis libur).',
    steps: [
      'Buka Kalender Akademik — grid bulan berjalan tampil.',
      'Klik tanggal kosong/masuk → pilih "Libur" + isi keterangan.',
      'Klik tanggal libur → kembalikan menjadi hari "Masuk".',
      'Akhir pekan (Sab/Ming) otomatis libur — dapat ditimpa bila ada kegiatan.',
      'Guru hanya melihat (read-only); hanya Admin yang mengubah.',
    ],
    watchouts: [
      'Tandai libur SEBELUM presensi diisi agar rekap harian ikut benar.',
      'Keterangan libur tampil sebagai tooltip pada kalender & rekap.',
    ],
    screen: 'kalender',
    screenTable: {
      caption: 'Legenda kalender',
      headers: ['Warna', 'Arti'],
      rows: [
        ['Putih', 'Hari masuk (dihitung rekap)'],
        ['Merah muda', 'Libur — presensi dinonaktifkan'],
        ['Tooltip', 'Keterangan libur (mis. libur nasional)'],
      ],
    },
  },
  {
    id: 'admin-monitoring',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah06',
    title: 'Monitoring Presensi',
    description: 'Memantau kelas yang belum mengisi presensi dan siswa berstatus Alfa — langsung dari dashboard.',
    goal: 'Menutup celah data: tidak ada hari efektif yang kosong tanpa sebab.',
    steps: [
      'Di Dashboard, baca strip amber "Perlu perhatian".',
      'Contoh: "1 kelas belum presensi" → klik tombol Lihat.',
      'Anda diarahkan ke Rekap dengan filter kelas & tanggal yang tepat.',
      'Ingatkan wali kelas via tombol "Isi Sekarang" (tautan presensi).',
      'Strip hijau "Semua kelas sudah presensi" = data hari ini komplit.',
    ],
    watchouts: [
      'Alfa harian tampil merah pada strip — tindak lanjuti sebelum rekap bulanan.',
      'Monitoring bergantung pada guru menekan Simpan Presensi.',
    ],
    screen: 'dashboard-admin',
    screenTable: {
      caption: 'Status monitoring22 Sep2026',
      headers: ['Kelas', 'Status'],
      rows: [
        ['5A', 'Sudah presensi (H8 I1 S1)'],
        ['5B', 'Sudah presensi (H9 S1)'],
        ['6A', 'Belum presensi — perlu tindak lanjut'],
      ],
    },
  },
  {
    id: 'admin-rekap',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah07',
    title: 'Rekap Bulanan',
    description: 'Matriks kehadiran per siswa untuk satu bulan — siap cetak PDF & unduh Excel.',
    goal: 'Menyediakan bukti presensi resmi bulanan untuk kepala madrasah/wali kelas.',
    steps: [
      'Buka Rekap Bulanan, pilih kelas, bulan, dan tahun.',
      'Tabel menampilkan sel H/I/S/A per tanggal (akhir pekan & libur diberi abu).',
      'Kolom kanan: jumlah H/I/S/A dan persentase per siswa.',
      'Klik "Cetak PDF" (kop surat otomatis) atau "Unduh Excel".',
      'Deep-link dari dashboard "kelas belum presensi" membuka filter otomatis.',
    ],
    watchouts: [
      'Sel kosong = kelas belum submit hari itu — bukan otomatis Hadir.',
      'Persentase dihitung atas hari yang benar-benar tercatat.',
    ],
    screen: 'rekap',
    screenTable: {
      caption: 'Ringkasan kelas5A · Sep2026',
      headers: ['Nama', 'H', 'I', 'S', 'A', '%'],
      rows: [
        ['Ahmad Fauzan', '15', '0', '0', '0', '100%'],
        ['Nabila Putri', '14', '1', '0', '0', '93%'],
        ['Rizky Maulana', '14', '0', '1', '0', '93%'],
        ['Yusuf Ibrahim', '11', '1', '1', '2', '73%'],
      ],
      note: '15 hari tercatat · data fiktif demo',
    },
  },
  {
    id: 'admin-semester',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah08',
    title: 'Rekap Semester',
    description: 'Perangkuman satu semester (mis. Ganjil: Jul–Des) per siswa — format siap rapor.',
    goal: 'Memberi gambaran kumulatif kehadiran satu kelas untuk evaluasi semester.',
    steps: [
      'Buka Rekap Semester, pilih kelas dan rentang tanggal.',
      'Sistem merangkum seluruh hari efektif tercatat dalam rentang.',
      'Lihat jumlah H/I/S/A kumulatif + persentase per siswa.',
      'Cetak PDF (format standar) atau unduh Excel.',
      'Rentang default mengikuti tahun ajaran aktif (Jul–Jan untuk Ganjil).',
    ],
    watchouts: [
      'Tanggal di masa depan tidak dihitung — rekap berjalan seiring semester.',
      'Pastikan bulan-bulan sebelumnya sudah lengkap presensinya.',
    ],
    screen: 'rekap-semester',
    screenTable: {
      caption: 'Rekap semester5A (13 Jul–22 Sep2026)',
      headers: ['Nama', 'H', 'I', 'S', 'A', '%'],
      rows: [
        ['Ahmad Fauzan', '50', '0', '0', '0', '100%'],
        ['Hamdan Fadhilah', '46', '0', '1', '3', '92%'],
        ['Nabila Putri', '49', '1', '0', '0', '98%'],
        ['Yusuf Ibrahim', '45', '2', '1', '2', '90%'],
      ],
      note: '50 hari efektif · data fiktif demo',
    },
  },
  {
    id: 'admin-statistik',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah09',
    title: 'Statistik Kehadiran',
    description: 'Persentase kehadiran bulan berjalan per siswa, diurut dari terendah untuk intervensi dini.',
    goal: 'Menemukan siswa berisiko sebelum masuk ke rekap resmi.',
    steps: [
      'Buka Statistik Kehadiran (filter kelas tersedia untuk Admin).',
      'Atur Ambang batas % (mis.90) — baris di bawah ambang ditandai merah.',
      'Baca kolom I/S/A, jumlah Hadir, hari tercatat, dan % bebas alfa.',
      'Kotak peringatan menampilkan jumlah siswa di bawah ambang.',
      'Gunakan paginasi bila banyak siswa.',
    ],
    watchouts: [
      '% bebas alfa = (hari tercatat − Alfa) / hari tercatat — konsisten dengan aplikasi.',
      'Urutan terendah-membantu prioritas pembinaan wali kelas.',
    ],
    screen: 'statistik',
    screenTable: {
      caption: 'Statistik kelas5A · Sep2026 (ambang90%)',
      headers: ['Nama', 'I', 'S', 'A', 'Hadir', '%'],
      rows: [
        ['Hamdan Fadhilah', '0', '1', '2', '12', '87%'],
        ['Yusuf Ibrahim', '1', '1', '2', '11', '87%'],
        ['Nabila Putri', '1', '0', '0', '14', '100%'],
        ['Ahmad Fauzan', '0', '0', '0', '15', '100%'],
      ],
      note: '2 siswa di bawah90% · data fiktif demo',
    },
  },
  {
    id: 'admin-library',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah10',
    title: 'Library / Perpustakaan',
    description: 'Admin memiliki akses penuh ke modul perpustakaan (bersama Pustakawan): koleksi, sirkulasi, laporan.',
    goal: 'Mengawasi operasional perpustakaan dari satu portal yang sama.',
    steps: [
      'Dashboard Perpustakaan: judul, eksemplar, dipinjam, terlambat.',
      'Data Koleksi: tambah/edit judul & jumlah stok fisik.',
      'Sirkulasi: catat peminjaman & konfirmasi pengembalian (stok otomatis).',
      'Data Pengunjung + Scanner QR kartu siswa untuk kunjungan cepat.',
      'Laporan: kunjungan & sirkulasi per periode.',
    ],
    watchouts: [
      'Stok berkurang saat dipinjam dan kembali saat dikembalikan — jangan edit stok manual untuk sirkulasi.',
      'Detail langkah ada di bagian Tutorial Perpustakaan.',
    ],
    screen: 'dashboard-perpus',
    screenTable: {
      caption: 'KPI perpustakaan',
      headers: ['Metrik', 'Nilai'],
      rows: [
        ['Total Judul', '128'],
        ['Total Eksemplar', '462'],
        ['Sedang Dipinjam', '37'],
        ['Terlambat', '4'],
      ],
    },
  },
  {
    id: 'admin-riwayat-log',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah11',
    title: 'Riwayat Kelas & Log Aktivitas',
    description: 'Jejak audit sekolah: histori kelas per siswa dan rekaman siapa mengubah apa, kapan.',
    goal: 'Menelusuri perubahan data dan menyelesaikan sengketa dengan bukti.',
    steps: [
      'Riwayat Kelas: pilih siswa → daftar kelas per tahun ajaran.',
      'Log Aktivitas:200 entri terbaru (filter aksi & rentang tanggal).',
      'Aksi terekam: input_presensi, update_kalender, sirkulasi perpus, dll.',
      'Kolom detail menampilkan ringkasan perubahan (ringkas).',
      'Gunakan pencarian untuk menemukan kejadian tertentu.',
    ],
    watchouts: [
      'Log bersifat append-only di aplikasi (tidak bisa diedit lewat UI).',
      'Bersihkan log hanya dari Pengaturan → Pemeliharaan (Admin senior).',
    ],
    screen: 'aktivitas',
    screenTable: {
      caption: 'Contoh log aktivitas',
      headers: ['Waktu', 'Aksi', 'Oleh', 'Record'],
      rows: [
        ['22 Sep07:35', 'input_presensi', 'Siti Rahmawati', '2026-09-22:5A'],
        ['22 Sep07:12', 'update_kalender', 'Budi Santoso', '2026-10-12'],
        ['21 Sep10:04', 'pinjam_buku', 'Nur Aini', 'Laskar Pelangi'],
      ],
    },
  },
  {
    id: 'admin-pengaturan',
    section: 'admin',
    role: 'admin',
    layout: 'feature',
    kicker: 'Admin · Langkah12',
    title: 'Pengaturan',
    description: 'Identitas madrasah, tahun ajaran, daftar kelas, kenaikan kelas, dan pemeliharaan data.',
    goal: 'Mengonfigurasi sistem sesuai kondisi madrasah — sekali setel, dipakai semua modul.',
    steps: [
      'Tab Identitas: nama madrasah, logo, teks kop surat PDF, daftar kelas.',
      'Tab Akademik: tahun ajaran & semester aktif, hari libur mingguan.',
      'Tab Kenaikan Kelas: proses akhir tahun (kelas naik, kelas6 lulus).',
      'Tab Pemeliharaan: cadangan Excel multi-sheet, reset data (zona berbahaya).',
      'Periode aktif tampil di header seluruh aplikasi.',
    ],
    watchouts: [
      'Kenaikan kelas TIDAK BISA dibatalkan — jalankan sekali di akhir Genap.',
      'Zona berbahaya menghapus data nyata; cadangkan dulu.',
    ],
    screen: 'pengaturan',
    screenTable: {
      caption: 'Tab Pengaturan',
      headers: ['Tab', 'Fungsi'],
      rows: [
        ['Identitas', 'Nama, logo, kop surat, daftar kelas'],
        ['Akademik', 'Tahun ajaran, semester, hari libur mingguan'],
        ['Kenaikan Kelas', 'Naik kelas massal akhir tahun'],
        ['Pemeliharaan', 'Backup Excel & reset data'],
      ],
    },
  },
]
