/** SECTION3 — GURU (divider +9 langkah). */

export const guruSlides = [
  {
    id: 'guru-divider',
    section: 'guru',
    role: 'guru',
    layout: 'divider',
    sectionNo: 3,
    title: 'Tutorial Guru',
    description: 'Alur wali kelas: dari Login hingga Help — presensi harian dalam hitungan detik.',
    sectionItems: [
      'Login',
      'Dashboard',
      'Pilih Kelas',
      'Input Presensi',
      'Status H/I/S/A',
      'Simpan Presensi',
      'Rekap Bulanan & Semester',
      'Statistik Kehadiran',
      'Kalender (read-only) & Help',
    ],
  },
  {
    id: 'guru-login',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah01',
    title: 'Bagaimana Guru Masuk',
    description: 'Guru menerima username & password dari Admin, lalu login seperti biasa. Sesi langsung terikat ke kelas binaan.',
    goal: 'Masuk dengan akun Guru sehingga menu presensi kelas sendiri terbuka.',
    steps: [
      'Buka halaman login aplikasi.',
      'Masukkan username (mis. guru.siti) dan password dari Admin.',
      'Tekan "Masuk Sekarang".',
      'Dashboard Guru menampilkan ringkasan kelas yang Anda wali.',
      'Jaringan bermasalah? Gunakan panel "Pulihkan Sesi" di bawah form.',
    ],
    watchouts: [
      'Akun Guru TIDAK bisa memilih kelas lain — dikunci sistem.',
      'Lupa password → hubungi Admin (reset dilakukan Admin).',
    ],
    screen: 'login',
    screenTable: {
      caption: 'Form login guru (demo)',
      headers: ['Field', 'Isi demo'],
      rows: [
        ['Username', 'guru.siti'],
        ['Password', '•••••••• (tidak ditampilkan)'],
        ['Hasil', 'Redirect ke Dashboard · Kelas5A'],
      ],
    },
  },
  {
    id: 'guru-dashboard',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah02',
    title: 'Dashboard Guru',
    description: 'Versi kelas-terbatas dari dashboard: hanya5A Anda, dengan strip status presensi hari ini.',
    goal: 'Tahu dalam5 detik: sudahkah kelas Anda presensi hari ini?',
    steps: [
      'Lihat strip atas: "Belum presensi" (amber) → tombol Isi Sekarang.',
      'Strip hijau "Semua kelas sudah presensi" = tugas hari ini selesai.',
      'KPI: Total Siswa kelas, Hadir, Izin, Sakit, Alfa hari ini.',
      'Tren kehadiran kelas Anda (7 hari / bulanan / tahunan).',
      'Donat komposisi + daftar nama siswa tidak hadir.',
    ],
    watchouts: [
      'Nama siswa tidak hadir tampil lengkap di sini — memudahkan absensi susulan.',
      'Aksi cepat: Input Presensi, Rekap, Statistik, Kalender.',
    ],
    screen: 'dashboard-guru',
    screenTable: {
      caption: 'KPI guru kelas5A ·22 Sep2026',
      headers: ['Metric', 'Nilai'],
      rows: [
        ['Total Siswa', '10'],
        ['Hadir', '8 ·80% kehadiran'],
        ['Izin / Sakit / Alfa', '1 /1/0'],
        ['Status', 'Sudah presensi hari ini'],
      ],
    },
  },
  {
    id: 'guru-pilih-kelas',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah03',
    title: 'Memilih Kelas di Input Presensi',
    description: 'Halaman Input Presensi dibuka; tanggal hari ini terisi otomatis. Guru hanya melihat kelas sendiri.',
    goal: 'Menyiapkan konteks presensi yang benar (tanggal + kelas) sebelum menandai.',
    steps: [
      'Klik menu Input Presensi (atau tombol dari dashboard).',
      'Field Tanggal default hari ini — boleh mundur untuk input susulan.',
      'Dropdown Kelas terkunci "5A" untuk guru (Admin bisa memilih semua kelas).',
      'Daftar siswa aktif kelas termuat otomatis, urut nama.',
      'Kotak "Cari siswa" untuk lompat cepat ke nama/NISN.',
    ],
    watchouts: [
      'Tanggal libur → form dinonaktifkan (alert merah muncul).',
      'Siswa pindahan/keluar tidak tampil (status non-aktif).',
    ],
    screen: 'presensi',
    screenTable: {
      caption: 'Konteks input presensi',
      headers: ['Field', 'Nilai'],
      rows: [
        ['Tanggal', '22 September2026 (Selasa)'],
        ['Kelas', '5A — terkunci untuk guru'],
        ['Siswa aktif', '10'],
        ['Status form', 'Sudah presensi · siap diperbarui'],
      ],
    },
  },
  {
    id: 'guru-status',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah04',
    title: 'Status Hadir / Izin / Sakit / Alfa',
    description: 'Sistem memakai pola pengecualian: semua siswa default Hadir — Anda hanya menandai yang TIDAK masuk.',
    goal: 'Mengisi presensi secepat mungkin tanpa mengklik32 kali.',
    steps: [
      'Tanyakan ke ketua kelas: "Siapa yang tidak masuk hari ini?"',
      'Klik status Izin / Sakit / Alfa pada kartu siswa yang berhalangan.',
      'Kartu berubah warna mengikuti status (biru/amber/merah).',
      'Opsional: "Tandai semua" bila kelas100% satu status.',
      'Ringkasan H/I/S/A di bawah ter-update langsung (angka hidup).',
    ],
    watchouts: [
      'Warna resmi: Hadir #047857 · Izin #0369A1 · Sakit #D97706 · Alfa #BE123C.',
      'Perubahan belum disimpan ditandai badge kuning "n perubahan belum disimpan".',
    ],
    screen: 'presensi',
    screenTable: {
      caption: 'Contoh penandaan kelas5A',
      headers: ['Siswa', 'Status', 'Alasan umum'],
      rows: [
        ['Nabila Putri', 'Izin', 'Keperluan keluarga'],
        ['Rizky Maulana', 'Sakit', 'Demam, surat menyusul'],
        ['8 siswa lainnya', 'Hadir', 'Default otomatis'],
      ],
    },
  },
  {
    id: 'guru-simpan',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah05',
    title: 'Menyimpan Presensi',
    description: 'Satu tekan Simpan → seluruh siswa kelas tercatat, log aktivitas ditulis, dashboard admin ter-update.',
    goal: 'Menetapkan data resmi hari itu untuk kelas Anda.',
    steps: [
      'Tekan tombol hijau "Simpan Presensi" (bilah bawah, selalu terlihat).',
      'Sukses → toast: "Presensi kelas5A tersimpan — H:8 I:1 S:1 A:0".',
      'Badge berubah menjadi "Tersimpan".',
      'Ubah data? Tombol berubah "Perbarui Presensi" + konfirmasi penimpanan.',
      'Meninggalkan halaman dengan perubahan belum disimpan → dialog peringatan.',
    ],
    watchouts: [
      'Simpan sebelum jam istirahat agar admin tidak menagih.',
      'Simpan ulang MENIMPA data lama — pastikan sudah final.',
      'Tutup tab browser juga diperingatkan bila ada perubahan disimpan.',
    ],
    screen: 'presensi',
    screenTable: {
      caption: 'Konfirmasi simpan',
      headers: ['Elemen', 'Nilai'],
      rows: [
        ['Tombol', 'Simpan Presensi → Tersimpan'],
        ['Ringkasan', 'H8 · I1 · S1 · A0'],
        ['Log', 'input_presensi2026-09-22:5A'],
        ['Dampak', 'Dashboard admin & rekap ter-update'],
      ],
    },
  },
  {
    id: 'guru-rekap',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah06',
    title: 'Melihat Rekap (Bulanan & Semester)',
    description: 'Guru melihat rekap kelasnya sendiri — pola yang sama dengan Admin, cakupan hanya kelas binaan.',
    goal: 'Memverifikasi data bulanan & menyiapkan cetakan untuk pimpinan.',
    steps: [
      'Rekap Bulanan: pilih bulan → matriks H/I/S/A per tanggal.',
      'Kolom persentase kanan = ringkasan per siswa.',
      'Rekap Semester: rentang otomatis mengikuti tahun ajaran aktif.',
      'Cetak PDF (kop surat madrasah) atau Unduh Excel.',
      'Sel abu-abu = akhir pekan/libur, sel kosong = belum disubmit.',
    ],
    watchouts: [
      'Jika ada sel kosong pada hari sekolah → kelas belum presensi hari itu.',
      'Persentase hanya menghitung hari yang benar-benar tercatat.',
    ],
    screen: 'rekap',
    screenTable: {
      caption: 'Rekap5A · Sep2026',
      headers: ['Nama', 'H', 'I', 'S', 'A', '%'],
      rows: [
        ['Ahmad Fauzan', '15', '0', '0', '0', '100%'],
        ['Nabila Putri', '14', '1', '0', '0', '93%'],
        ['Yusuf Ibrahim', '11', '1', '1', '2', '73%'],
      ],
      note: 'Guru hanya melihat kelas sendiri (5A)',
    },
  },
  {
    id: 'guru-statistik',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah07',
    title: 'Melihat Statistik Kehadiran',
    description: 'Persentase bulan berjalan per siswa — guru tanpa filter kelas (terkunci5A).',
    goal: 'Membina siswa yang kehadirannya turun, sebelum jadi masalah rapor.',
    steps: [
      'Buka Statistik Kehadiran.',
      'Atur ambang batas % (mis.90) sesuai kebijakan madrasah.',
      'Baris merah = siswa di bawah ambang (urutan terendah di atas).',
      'Kolom I/S/A membantu mengenali pola (sering sakit vs sering alfa).',
      'Diskusikan dengan wali kelas/ BK untuk siswa berisiko.',
    ],
    watchouts: [
      'Statistik dihitung bulan berjalan — reset setiap1 tanggal.',
      'Data hanya muncul setelah ada presensi tersubmit.',
    ],
    screen: 'statistik',
    screenTable: {
      caption: 'Statistik5A (ambang90%)',
      headers: ['Nama', 'I', 'S', 'A', '%'],
      rows: [
        ['Hamdan Fadhilah', '0', '1', '2', '87%'],
        ['Yusuf Ibrahim', '1', '1', '2', '87%'],
        ['Nabila Putri', '1', '0', '0', '100%'],
      ],
      note: '2 siswa di bawah ambang',
    },
  },
  {
    id: 'guru-kalender-help',
    section: 'guru',
    role: 'guru',
    layout: 'feature',
    kicker: 'Guru · Langkah08',
    title: 'Kalender Akademik (Read-only) & Help',
    description: 'Guru melihat kalender tanpa bisa mengubah; bantuan lengkap tersedia di menu Panduan.',
    goal: 'Tahu hari efektif tanpa menunggu info — dan tahu ke mana meminta bantuan.',
    steps: [
      'Buka Kalender: tanggal libur/masuk terlihat jelas.',
      'Tombol toggle TIDAK aktif untuk Guru — hanya Admin yang mengubah.',
      'Alasan: kalender memengaruhi seluruh rekap — dijaga pusat oleh Admin.',
      'Buka menu Panduan Penggunaan (ikon tanda tanya di sidebar).',
      'Panduan menampilkan langkah per peran + solusi masalah umum.',
    ],
    watchouts: [
      'Ada usulan hari libur? Ajukan ke Admin — jangan dicatat manual.',
      'Layar putih/blank → minta Admin jalankan "Refresh App" atau hapus cache browser.',
    ],
    screen: 'kalender',
    screenTable: {
      caption: 'Hak akses kalender',
      headers: ['Peran', 'Lihat', 'Ubah'],
      rows: [
        ['Admin', 'Ya', 'Ya'],
        ['Guru', 'Ya', 'Tidak (read-only)'],
        ['Pustakawan', 'Tidak di menu', 'Tidak'],
      ],
    },
  },
  {
    id: 'guru-summary',
    section: 'guru',
    role: 'guru',
    layout: 'grid',
    kicker: 'Guru · Ringkasan',
    title: 'Rutinitas Harian Wali Kelas',
    description: 'Lima menit setiap pagi menjaga seluruh sistem tetap akurat.',
    cards: [
      { title: '1 · Buka Input Presensi', body: 'Login → menu Input Presensi. Tanggal & kelas sudah terisi.', icon: 'clipboard' },
      { title: '2 · Tandai pengecualian', body: 'Hanya siswa Izin / Sakit / Alfa — sisanya default Hadir.', icon: 'users' },
      { title: '3 · Simpan', body: 'Tekan Simpan Presensi, pastikan toast sukses muncul.', icon: 'check' },
      { title: '4 · Cek dashboard', body: 'Strip hijau "semua sudah presensi" = tuntas.', icon: 'chart' },
      { title: '5 · Awal bulan', body: 'Cek Rekap Bulanan & tanda tangani cetakan untuk pimpinan.', icon: 'sheet' },
      { title: 'Saat bingung', body: 'Menu Panduan Penggunaan atau halaman /tutorial ini.', icon: 'help' },
    ],
  },
]
