/** SECTION1 — INTRODUCTION (5 slides). */

export const introSlides = [
  {
    id: 'cover',
    section: 'intro',
    role: 'all',
    layout: 'cover',
    title: 'Tutorial Presensi Siswa',
    subtitle: 'Sistem Presensi & Perpustakaan Madrasah — User Guide & Presentasi Interaktif',
    meta: ['Dokumentasi resmi aplikasi', 'Mode presentasi 16:9', 'Ekspor PDF & PPTX'],
    coverStats: [
      { label: 'Peran pengguna', value: '3', sub: 'Admin · Guru · Pustakawan' },
      { label: 'Modul', value: '2', sub: 'Presensi & Perpustakaan' },
      { label: 'Data demo', value: '100%', sub: 'Fiktif & lokal' },
    ],
  },
  {
    id: 'intro-what',
    section: 'intro',
    role: 'all',
    layout: 'feature',
    kicker: 'Pendahuluan',
    title: 'Apa Itu Sistem Ini?',
    description:
      'Portal terpadu madrasah untuk mencatat kehadiran siswa harian, merangkum rekap akademik, dan mengelola sirkulasi perpustakaan — satu aplikasi, satu data.',
    goal: 'Memahami cakupan aplikasi sebelum masuk ke langkah per peran.',
    steps: [
      'Presensi harian per kelas oleh wali kelas, pola pengecualian (default Hadir).',
      'Rekap bulanan & semester siap cetak PDF/Excel untuk Kepala Madrasah.',
      'Statistik kehadiran dengan ambang batas untuk intervensi dini.',
      'Kalender akademik: hari masuk & libur memengaruhi perhitungan.',
      'Perpustakaan: katalog, sirkulasi, kunjungan, kartu anggota QR.',
      'Semua aksi tercatat di Log Aktivitas (audit trail).',
    ],
    watchouts: [
      'Aplikasi membutuhkan akun login sesuai peran — tidak untuk publik.',
      'Halaman /tutorial ini terbuka tanpa login (dokumentasi publik).',
    ],
    screen: 'dashboard-admin',
    screenTable: {
      caption: 'Ringkasan fitur utama',
      headers: ['Modul', 'Isi'],
      rows: [
        ['Presensi', 'Input harian, rekap bulanan & semester, statistik'],
        ['Master Data', 'Siswa, Guru & Wali Kelas, Riwayat Kelas'],
        ['Akademik', 'Kalender, Tahun Ajaran, Pengaturan'],
        ['Perpustakaan', 'Koleksi, Sirkulasi, Kunjungan, Laporan'],
        ['Keamanan', 'Login, Session, Role, Protected route'],
      ],
    },
  },
  {
    id: 'intro-features',
    section: 'intro',
    role: 'all',
    layout: 'grid',
    kicker: 'Pendahuluan',
    title: 'Fitur Utama',
    description: 'Enam kelompok fitur yang saling terhubung dalam satu alur data.',
    cards: [
      { title: 'Input Presensi', body: 'Tandai Hadir / Izin / Sakit / Alfa per siswa, simpan per kelas & tanggal.', icon: 'clipboard' },
      { title: 'Rekap & Cetak', body: 'Matriks bulanan, rekap semester, ekspor PDF & Excel siap distribusi.', icon: 'sheet' },
      { title: 'Statistik Kehadiran', body: 'Persentase per siswa, urut terendah, peringatan di bawah ambang.', icon: 'chart' },
      { title: 'Master Data', body: 'Kelola siswa, akun guru/wali kelas, mutasi, dan riwayat kelas.', icon: 'users' },
      { title: 'Kalender Akademik', body: 'Tandai hari masuk/libur; akhir pekan otomatis libur.', icon: 'calendar' },
      { title: 'Perpustakaan', body: 'Katalog, peminjaman-pengembalian, kunjungan, kartu QR.', icon: 'book' },
    ],
  },
  {
    id: 'intro-roles',
    section: 'intro',
    role: 'all',
    layout: 'grid',
    kicker: 'Pendahuluan',
    title: 'Tiga Peran Pengguna',
    description: 'Setiap peran melihat menu yang berbeda — dijaga oleh role pada session login.',
    cards: [
      { title: 'Admin', body: 'Kuasa penuh: master data, kalender, monitoring semua kelas, pengaturan, log aktivitas.', icon: 'shield' },
      { title: 'Guru / Wali Kelas', body: 'Input presensi kelas yang ditugaskan, rekap & statistik kelasnya, kalender baca-saja.', icon: 'graduation' },
      { title: 'Pustakawan', body: 'Modul perpustakaan: koleksi, sirkulasi, kunjungan, kartu anggota, laporan.', icon: 'library' },
    ],
    bullets: [
      'Akun dibuat oleh Admin pada menu Guru & Wali Kelas.',
      'Role "Guru & Pustakawan" menggabungkan dua akses bila diperlukan.',
      'Pembatasan sesungguhnya juga ditegakkan server-side (RLS).',
    ],
  },
  {
    id: 'intro-flow',
    section: 'intro',
    role: 'all',
    layout: 'flow',
    kicker: 'Pendahuluan',
    title: 'Gambaran Alur Sistem',
    description: 'Dari data dasar hingga laporan — satu siklus yang berulang setiap hari sekolah.',
    flow: [
      { label: 'Login', sub: 'peran' },
      { label: 'Master Data', sub: 'siswa & guru' },
      { label: 'Kalender', sub: 'hari efektif' },
      { label: 'Input Presensi', sub: 'wali kelas' },
      { label: 'Monitoring', sub: 'admin' },
      { label: 'Rekap', sub: 'bulanan/semester' },
      { label: 'Statistik', sub: 'intervensi' },
    ],
    watchouts: ['Alur harian: Guru input presensi di pagi hari → Admin memantau → rekap di akhir bulan/semester.'],
  },
]
