/** SECTION4 — LIBRARY / PUSTAKAWAN (hanya fitur yang ada di source code). */

export const librarySlides = [
  {
    id: 'library-divider',
    section: 'library',
    role: 'pustakawan',
    layout: 'divider',
    sectionNo: 4,
    title: 'Tutorial Perpustakaan',
    description: 'Alur Pustakawan — semua fitur di bawah ini ada pada source code aplikasi.',
    sectionItems: [
      'Beranda Perpustakaan',
      'Data Koleksi (Buku)',
      'Peminjaman (Sirkulasi)',
      'Pengembalian',
      'Stok',
      'Kunjungan & Scan QR',
      'Kartu Anggota',
      'Laporan',
    ],
  },
  {
    id: 'library-dashboard',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·01',
    title: 'Beranda Perpustakaan',
    description: 'KPI koleksi & sirkulasi, tren kunjungan vs peminjaman, dan lima transaksi terbaru.',
    goal: 'Satu layar untuk mengetahui denyut perpustakaan hari ini.',
    steps: [
      'KPI: Total Judul, Total Eksemplar, Sedang Dipinjam, Terlambat.',
      'Grafik tren: Harian / Bulanan / Tahunan (kunjungan & peminjaman).',
      'Kartu "Peminjaman Terakhir":5 transaksi terbaru.',
      'Aksi cepat: Sirkulasi, Data Koleksi, Pengunjung, Laporan.',
      'Menu sidebar kategori PERPUSTAKAAN untuk navigasi lengkap.',
    ],
    watchouts: [
      'Angka Terlambat merah → segera tagih ke peminjam.',
      'Semua angka demo pada tutorial ini fiktif.',
    ],
    screen: 'dashboard-perpus',
    screenTable: {
      caption: 'KPI perpustakaan',
      headers: ['Metrik', 'Nilai'],
      rows: [
        ['Total Judul', '128'],
        ['Total Eksemplar', '462'],
        ['Sedang Dipinjam', '37'],
        ['Terlambat', '4'],
        ['Kunjungan hari ini', '24'],
      ],
    },
  },
  {
    id: 'library-buku',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·02',
    title: 'Data Koleksi (Buku)',
    description: 'Katalog judul beserta stok fisik. Buku wajib terdaftar sebelum bisa dipinjam.',
    goal: 'Menjaga katalog lengkap dan stok terpercaya.',
    steps: [
      'Buka Data Koleksi → daftar judul + Total/Pinjam/Sisa per baris.',
      'Tambah buku: judul, pengarang, penerbit, tahun, jumlah stok.',
      'Edit untuk perbaiki data; hapus hanya bila salah input.',
      'Import Excel untuk input massal awal tahun.',
      'Ikon riwayat per judul → siapa pernah meminjam buku itu.',
    ],
    watchouts: [
      'Kolom Sisa = stok − dipinjam; jangan edit stok untuk mencatat peminjaman.',
      'Buku hilang/rusak: kurangi stok lewat Edit, lalu catat keterangannya.',
    ],
    screen: 'buku',
    screenTable: {
      caption: 'Contoh katalog',
      headers: ['Judul', 'Tahun', 'Total', 'Pinjam', 'Sisa'],
      rows: [
        ['Laskar Pelangi', '2005', '5', '2', '3'],
        ['Bumi Manusia', '1980', '4', '1', '3'],
        ['Perahu Kertas', '2010', '4', '2', '2'],
        ['Dilan1990', '2014', '6', '3', '3'],
      ],
      note: '1–6 dari128 judul · data fiktif demo',
    },
  },
  {
    id: 'library-peminjaman',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·03',
    title: 'Peminjaman (Sirkulasi)',
    description: 'Mencatat peminjaman baru: pilih siswa & buku, tanggal pinjam tercatat otomatis, stok berkurang.',
    goal: 'Sirkulasi cepat tanpa buku catatan manual.',
    steps: [
      'Buka Sirkulasi → tab "Sedang Dipinjam".',
      'Klik "+ Catat Peminjaman" → pilih siswa (bisa cari NIS/nama).',
      'Pilih buku — hanya judul dengan sisa stok >0.',
      'Tanggal pinjam otomatis; tanggal kembali mundur7 hari (dapat diatur).',
      'Simpan → baris muncul berstatus "Dipinjam", stok judul −1.',
    ],
    watchouts: [
      'Siswa dengan tunggakan tetap boleh meminjam? Ikuti kebijakan madrasah — sistem menampilkan riwayatnya.',
      'Peminjaman tercatat di Log Aktivitas (audit).',
    ],
    screen: 'sirkulasi',
    screenTable: {
      caption: 'Sirkulasi aktif',
      headers: ['Siswa', 'Buku', 'Pinjam', 'Kembali', 'Status'],
      rows: [
        ['Ahmad Fauzan', 'Laskar Pelangi', '19 Sep', '26 Sep', 'Dipinjam'],
        ['Rizky Maulana', 'Perahu Kertas', '08 Sep', '15 Sep', 'Terlambat7 hari'],
        ['Nabila Putri', 'Bumi Manusia', '12 Sep', '19 Sep', 'Dikembalikan'],
      ],
    },
  },
  {
    id: 'library-pengembalian',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·04',
    title: 'Pengembalian',
    description: 'Cari peminjaman aktif, konfirmasi pengembalian — stok kembali otomatis dan status berubah.',
    goal: 'Menutup siklus pinjam dengan satu klik dan data yang selalu cocok.',
    steps: [
      'Di tab "Sedang Dipinjam", cari nama siswa (atau gunakan pencarian).',
      'Klik tombol "Kembalikan / Selesaikan" pada barisnya.',
      'Dialog konfirmasi menampilkan judul & tanggal pinjam.',
      'Konfirmasi → status "Dikembalikan", stok judul +1 otomatis.',
      'Tab "Semua Riwayat" menyimpan arsip lengkap (termasuk terlambat).',
    ],
    watchouts: [
      'Buku hilang saat pengembalian? Tandai lewat catatan & kurangi stok terpisah.',
      'Status "Terlambat" dihitung otomatis dari tanggal kembali.',
    ],
    screen: 'sirkulasi',
    screenTable: {
      caption: 'Alur pengembalian',
      headers: ['Langkah', 'Hasil'],
      rows: [
        ['Cari "Nabila Putri"', '1 pinjam aktif → selesai'],
        ['Kembalikan Bumi Manusia', 'Status: Dikembalikan'],
        ['Efek stok', 'Bumi Manusia:1 →2 tersedia'],
        ['Arsip', 'Tetap di "Semua Riwayat"'],
      ],
    },
  },
  {
    id: 'library-stok',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·05',
    title: 'Stok',
    description: 'Tiga kolom kunci di Data Koleksi: Total eksemplar, sedang dipinjam, dan sisa tersedia.',
    goal: 'Mengetahui kapan harus menggandakan koleksi populer.',
    steps: [
      'Buka Data Koleksi, perhatikan kolom Total / Pinjam / Sisa.',
      'Sisa0 → judul sedang habis dipinjam (antrean di luar sistem).',
      'Urutkan kolom untuk melihat judul paling banyak dipinjam.',
      'Edit stok bila ada pembelian/kerusakan buku fisik.',
      'Cek KPI "Sedang Dipinjam" di beranda untuk beban sirkulasi.',
    ],
    watchouts: [
      'Sisa stok juga yang menentukan buku bisa dipilih di form peminjaman.',
      'Stok fisik dikuratori berkala (mis. hilang1 eksemplar → edit total).',
    ],
    screen: 'buku',
    screenTable: {
      caption: 'Status stok (potongan katalog)',
      headers: ['Judul', 'Total', 'Pinjam', 'Sisa'],
      rows: [
        ['Laskar Pelangi', '5', '2', '3'],
        ['Sang Pemimpi', '3', '0', '3'],
        ['Dilan1990', '6', '3', '3'],
      ],
    },
  },
  {
    id: 'library-kunjungan',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·06',
    title: 'Kunjungan & Scan QR',
    description: 'Pencatatan pengunjung harian — manual lewat dropdown siswa, atau super cepat via scanner QR kartu.',
    goal: 'Data kunjungan lengkap untuk laporan akreditasi perpustakaan.',
    steps: [
      'Buka Data Pengunjung → pilih tanggal → daftar pengunjung tampil.',
      'Manual: pilih nama siswa di kartu "Catat Pengunjung", simpan.',
      'Cepat: klik "Buka Scanner QR" → arahkan kamera ke kartu siswa.',
      'QR terbaca → kunjungan tercatat + riwayat pindaian hari ini.',
      'Tekan Kembali untuk keluar dari mode scanner.',
    ],
    watchouts: [
      'Kamera butuh izin browser (HTTPS/localhost).',
      'Kunjungan salah rekam → hapus barisnya (ikon tempat sampah).',
    ],
    screen: 'kunjungan',
    screenTable: {
      caption: 'Kunjungan22 Sep2026',
      headers: ['Jam', 'Siswa', 'Kelas'],
      rows: [
        ['09:15', 'Ahmad Fauzan', '5A'],
        ['09:20', 'Nabila Putri', '5A'],
        ['10:02', 'Bilqis Nuraini', '5B'],
        ['10:18', 'Ilham Fauzi', '6A'],
      ],
      note: '24 pengunjung tercatat hari ini (demo)',
    },
  },
  {
    id: 'library-kartu',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·07',
    title: 'Kartu Anggota (Cetak QR)',
    description: 'Kartu bolak-balik ber-QR NISN: sisi depan identitas + QR, sisi belakang tata tertib.',
    goal: 'Menyiapkan kartu fisik anggota yang bisa dipindai scanner kunjungan.',
    steps: [
      'Buka menu Kartu Anggota → pilih kelas → siswa termuat.',
      'Pratinjau dua desain otomatis: depan & belakang (berdampingan).',
      'Klik "Download PDF" atau tekan Ctrl+P.',
      'Cetak di kertas tebal → potong → lipat tengah → laminasi.',
      'QR berisi NISN — dipakai scanner kunjungan & sirkulasi.',
    ],
    watchouts: [
      'Cetak tanpa skala "fit to page" agar ukuran kartu standar.',
      'QR jangan ditimpa stiker/laminasi buram agar mudah dipindai.',
    ],
    screen: 'kartu',
    screenTable: {
      caption: 'Komponen kartu',
      headers: ['Sisi', 'Isi'],
      rows: [
        ['Depan', 'Nama, NISN, kelas, logo, QR NISN'],
        ['Belakang', 'Tata tertib perpustakaan'],
        ['Format', 'PDF siap cetak, siswa per kelas'],
      ],
    },
  },
  {
    id: 'library-laporan',
    section: 'library',
    role: 'pustakawan',
    layout: 'feature',
    kicker: 'Pustakawan ·08',
    title: 'Laporan Perpustakaan',
    description: 'Laporan kunjungan & sirkulasi per periode: pengunjung teraktif, buku favorit, peminjam teraktif.',
    goal: 'Laporan berkala untuk kepala madrasah & akreditasi.',
    steps: [
      'Buka Laporan Perpustakaan.',
      'Pilih jenis: Laporan Kunjungan / Laporan Sirkulasi.',
      'Pilih periode: Harian / Bulanan / Tahunan / Sepanjang Waktu.',
      'Kartu ringkasan + peringkat (pengunjung, buku favorit, peminjam).',
      'Ekspor mengikuti pola rekap: siap dibagikan sebagai PDF.',
    ],
    watchouts: [
      'Periode default bulan berjalan — ganti bila butuh arsip bulan lalu.',
      'Kosong? Belum ada kunjungan/pinjam pada periode itu.',
    ],
    screen: 'laporan-perpus',
    screenTable: {
      caption: 'Ringkasan Sep2026',
      headers: ['Metrik', 'Nilai'],
      rows: [
        ['Total kunjungan', '342'],
        ['Total peminjaman', '89'],
        ['Teraktif (kunjungan)', 'Nabila Putri ·14 kali'],
        ['Buku terfavorit', 'Laskar Pelangi ·11 kali'],
      ],
    },
  },
]
